language: julia
os:
    - linux
julia:
    - 1.0
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
after_success:
- julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

- echo $TRAVIS_JULIA_VERSION
env:
- CODECOV_TOKEN="257536e4-7c71-4d18-b459-443db91d2870"
